### ISSUE TITLE
Does not build if WindowsAppSDKSelfContained is true

### ISSUE THREAD

**Issue by rossirpaulo** [Azure-Samples/ms-identity-netcore-winui#6]
If we add the following code to the .csproj file the project does not build:
`<PropertyGroup>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
</PropertyGroup>`

Is there any way to fix this or is the bug planned to be revised?

**Comment by kalyankrishna1** [comment]
It’s not a bug, but seems like a issue in the SDK . We advise you follow this one up with the windows SDK team

**Comment by rossirpaulo** [comment]
Therefore, it is a bug.
