### ISSUE TITLE
The Project doesn't know how to run the profile with name 'WinUIMSALApp(Package)' and command 'MsixPackage'.

### ISSUE THREAD

**Issue by gangjig** [Azure-Samples/ms-identity-netcore-winui#8]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
I followed the instruction, replaced with my client id and tenant id. When pressing F5 or pressing the button of WinUIMSALApp to debug/execute the solution from VS, got the error: The Project doesn't know how to run the profile with name 'WinUIMSALApp(Package)' and command 'MsixPackage'.

Using VS 2022. Tried to run as administrator, same error.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
>
10
### Mention any other details that might be useful
Visual studio 2022
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by v-michaelmi** [comment]
@gangjig do you know what version of Visual Studio 2022 you're currently using?

If it's older than version **17.1** you might be missing [single-project MSIX](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp) feature.

**Comment by Scottlis26** [comment]
I'm using Version 17.6.5 and have the same error. Is the XAML code no longer supported? If so, can you recommend a working Windows Desktop example solution that authenticates and uses Azure http trigger functions.

**Comment by Scottlis26** [comment]
Updated Visual Studio 2022 to Add >NET Multi-platform App UI development and Universal Windows Platform development and changed the Windows Settings, For Developers to turn on Developer Mode. It looks like it's running now through the command line.

**Comment by gangjig** [comment]
Thank you for sharing Scott. I will close this thread then.
